using System.Diagnostics.CodeAnalysis;

namespace WzPipeline.Domains.Gear;

[SuppressMessage("ReSharper", "InconsistentNaming")]
public enum GearPropType
{
    incARC = 1,
    incAUT,
    incSTR,
    incSTRr,
    incDEX,
    incDEXr,
    incINT,
    incINTr,
    incLUK,
    incLUKr,
    incAllStat_incMHP25,
    incAllStat_incMHP50_incMMP50,
    incAllStat,
    statR,
    incMHP_incMMP,
    incMHPr_incMMPr,
    incMHP,
    incMHPr,
    incMMP,
    incMMPr,
    incMDF,
    incPAD_incMAD,
    incPAD,
    incMAD,
    incAD,
    incPDD_incMDD,
    incPDD,
    incMDD,
    incACC_incEVA,
    incACC,
    incEVA,
    incSpeed,
    incJump,
    incCraft,
    attackSpeed,
    knockback,
    incPVPDamage,
    damR,
    bdR,
    incBDR,
    imdR,
    incIMDR,
    nbdR,
    incCHUC,
    incPQEXPr,

    //潜能属性
    incPADr = 100,
    incMADr,
    incPDDr,
    incMDDr,
    incACCr,
    incEVAr,
    incCr,
    incCDr,
    incDAMr,
    RecoveryHP,
    RecoveryMP,
    face,
    prop,
    time,
    HP,
    MP,
    attackType,
    ignoreTargetDEF,
    ignoreDAM,
    ignoreDAMr,
    DAMreflect,
    mpconReduce,
    mpRestore,
    incMesoProp,
    incRewardProp,
    incAllskill,
    RecoveryUP,
    boss,
    level,
    incTerR,
    incAsrR,
    incEXPr,
    reduceCooltime,
    incCriticaldamageMax,
    incCriticaldamageMin,
    @sealed,
    incSTRlv,
    incDEXlv,
    incINTlv,
    incLUKlv,
    incMaxDamage,
    incMHPlv,
    incPADlv,
    incMADlv,
    incCriticaldamage,

    Option,
    OptionToMob,
    activeSkill,
    bonusByTime,

    //特殊装备属性
    //attackSpeed = 200,
    tuc = 200,
    setItemID,
    durability,
    reqCraft,
    cash,
    royalSpecial,
    masterSpecial,
    reduceReq,

    //技能特有属性
    mastery = 300,

    //criticaldamageMin,
    //criticaldamageMax,
    criticaldamage,
    epad,
    emad,
    epdd,
    emdd,
    emhp,
    emmp,
    smartpad,
    smartacc,
    smarteva,

    //装备特有属性
    reqLevel = 1000,
    reqSTR,
    reqDEX,
    reqINT,
    reqLUK,
    reqJob,
    reqPOP,
    reqSpecJob,
    reqWeekDay, //要求日子
    grade,

    only = 1100,

    //notSale,
    //dropBlock,
    tradeBlock,
    accountSharable,
    accountSharableAfterExchange,
    onlyEquip,
    tradeAvailable,
    equipTradeBlock,
    sharableOnce,
    notExtend,
    epicItem,
    charismaEXP,
    senseEXP,
    insightEXP,
    willEXP,
    craftEXP,
    charmEXP,
    cashForceCharmExp,
    accountShareTag,
    noPotential,
    fixedPotential,
    timeLimited,
    specialGrade,
    fixedGrade,
    unchangeable,
    superiorEqp,

    //incPQEXPr,
    limitBreak,
    nActivatedSocket,
    jokerToSetItem,
    medalTag,
    chatBalloon,
    nameTag,
    ringOptionSkill,
    ringOptionSkillLv,
    abilityTimeLimited,
    blockGoldHammer,
    exceptUpgrade,
    colorvar,
    noMoveToLocker,
    onlyUpgrade,
    cantRepair,
    noPetEquipStatMoveItem,
    BTSLabel,
    BLACKPINKLabel,
    android,
    noLookChange,
    tucIgnoreForPotential,
    Etuc,
    CuttableCount,
    illusionGrade,
    limitedLabel,
    noPrism,
    noTradeLimitCash,
    magicLayerWz2,
    setExtraOption,
    reissueBan,

    //MSN专属属性
    blockUpgradeExtraOption,
    blockUpgradeStarforce,
    mintable,

    gatherTool_incSkillLevel = 2000,
    gatherTool_incSpeed,
    gatherTool_incNum,
    gatherTool_reqSkillLevel,


    // Custom
    bossReward = 10001,
    exUpgradeBlock,
    exUpgradeChangeBlock,

    // Ignored
    islot,
    vslot,
    price,
    slotMax,
    notSale,
    noDrop,
    undecomposable,
    unsyntesizable,
    exItem,
    exGrade,
    epic,
    expireOnLogout,
    expireOnNonPremiumLogin,
    variableStat,
    exceptToadsHammer,
    exceptTransmission,
    cubeExBaseOptionLevel,
    gatherTool,
    invisibleFace,
    collabo,
    equipDrop,
    specialID,
    tutorial,

    icnSTR,
    tradBlock,
    bonusExp,
    MaxHP,
    speed,
    incHP,
    addtion,
    additon,
    noExtend,
    hitDamRatePlus,
    hitDamRatePlus2,

    sfx,
    walk,
    stand,
    attack,
    afterImage,

    info,
    recovery,
    jewelCraft,
    scope,
    replace,
    StarPlanet,
    dayOfWeekItemStat,
    randVariation,
    icon2,
    icon3,
    icon4,
    icon5,
    icon6,
    icon7,
    iconRaw2,
    iconRaw3,
    iconRaw4,
    iconRaw5,
    iconRaw6,
    iconRaw7,
    iconD,
    iconRawD,
    toolTipPreview,
    dialogPreview,
    androidAni,
    removeEar,
    quest,
    noPotentialFieldtype,
    lookChangeType,
    sample,
    linkedPairItem,
    effect,
    reqSpecJobs,
    pmdR,
    fs,
    head,
    scanTradeBlock,
    kaiserOffsetY,
    incAttackCount,
    kaiserOffsetX,
    equippedEmotion,
    equippedSound,
    image,
    onlyCash,
    baseLevel,
    origin,
}